//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ampbi.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentSummary
    {
        public int AgentSummaryId { get; set; }
        public string Agent { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> LoginCount { get; set; }
        public Nullable<int> CallsHandled { get; set; }
        public Nullable<int> staffhoursinsecs { get; set; }
        public string StaffHours { get; set; }
        public Nullable<System.DateTime> InitialLoginTime { get; set; }
        public Nullable<System.DateTime> FinalLogoutTime { get; set; }
        public string Occupancy { get; set; }
        public Nullable<int> IdleCount { get; set; }
        public string TotalIdleTime { get; set; }
        public Nullable<int> TotalIdleTimeinsecs { get; set; }
        public string AverageIdleTime { get; set; }
        public Nullable<int> AverageIdleTimeinsecs { get; set; }
        public Nullable<int> AvailableCount { get; set; }
        public string TotalAvailableTime { get; set; }
        public Nullable<int> TotalAvailableTimeinsecs { get; set; }
        public string AverageAvailableTime { get; set; }
        public Nullable<int> AverageAvailableTimeinsecs { get; set; }
        public Nullable<int> InboundReservedCount { get; set; }
        public string TotalInboundReservedTime { get; set; }
        public Nullable<int> TotalInboundReservedTimeinsecs { get; set; }
        public string AverageInboundReservedTime { get; set; }
        public Nullable<int> AverageInboundReservedTimeinsecs { get; set; }
        public Nullable<int> InboundHoldCount { get; set; }
        public Nullable<int> InboundConnectedCount { get; set; }
        public string TotalInboundTalkTime { get; set; }
        public Nullable<int> TotalInboundTalkTimeinsecs { get; set; }
        public string TotalInboundHoldTime { get; set; }
        public Nullable<int> TotalInboundHoldTimeinsecs { get; set; }
        public string TotalInboundConnectedTime { get; set; }
        public Nullable<int> TotalInboundConnectedTimeinsecs { get; set; }
        public string AverageInboundHoldTime { get; set; }
        public Nullable<int> AverageInboundHoldTimeinsecs { get; set; }
        public string AverageInboundConnectedTime { get; set; }
        public Nullable<int> AverageInboundConnectedTimeinsecs { get; set; }
        public Nullable<int> OutDialReservedCount { get; set; }
        public string TotalOutDialReservedTime { get; set; }
        public Nullable<int> TotalOutDialReservedTimeinsecs { get; set; }
        public string AverageOutDialReservedTime { get; set; }
        public Nullable<int> AverageOutDialReservedTimeinsecs { get; set; }
        public Nullable<int> OutdialAttemptedCount { get; set; }
        public Nullable<int> OutdialConnectedCount { get; set; }
        public Nullable<int> OutdialHoldCount { get; set; }
        public string TotalOutdialTalkTime { get; set; }
        public Nullable<int> TotalOutdialTalkTimeinsecs { get; set; }
        public string TotalOutdialHoldTime { get; set; }
        public Nullable<int> TotalOutdialHoldTimeinsecs { get; set; }
        public string TotalOutdialConnectedTime { get; set; }
        public Nullable<int> TotalOutdialConnectedTimeinsecs { get; set; }
        public string AverageOutdialHoldTime { get; set; }
        public Nullable<int> AverageOutdialHoldTimeinsecs { get; set; }
        public string AverageOutdialConnectedTime { get; set; }
        public Nullable<int> AverageOutdialConnectedTimeinsecs { get; set; }
        public Nullable<int> DisconnectedCount { get; set; }
        public Nullable<int> InboundWrapUpCount { get; set; }
        public string TotalInboundWrapUpTime { get; set; }
        public Nullable<int> TotalInboundWrapUpTimeinsecs { get; set; }
        public string AverageInboundWrapUpTime { get; set; }
        public Nullable<int> AverageInboundWrapUpTimeinsecs { get; set; }
        public Nullable<int> OutdialWrapUpCount { get; set; }
        public string TotalOutdialWrapUptime { get; set; }
        public Nullable<int> TotalOutdialWrapUptimeinsecs { get; set; }
        public string AverageOutdialWrapUpTime { get; set; }
        public Nullable<int> AverageOutdialWrapUpTimeinsecs { get; set; }
        public Nullable<int> NotRespondingCount { get; set; }
        public string TotalNotRespondingTime { get; set; }
        public Nullable<int> TotalNotRespondingTimeinsecs { get; set; }
        public string AverageNotRespondingTime { get; set; }
        public Nullable<int> AverageNotRespondingTimeinsecs { get; set; }
        public Nullable<int> ConsultAnswerCount { get; set; }
        public string TotalConsultAnswerTime { get; set; }
        public Nullable<int> TotalConsultAnswerTimeinsecs { get; set; }
        public string AverageConsultAnswerTime { get; set; }
        public Nullable<int> AverageConsultAnswerTimeinsecs { get; set; }
        public Nullable<int> ConsultRequestCount { get; set; }
        public string TotalConsultRequestTime { get; set; }
        public Nullable<int> TotalConsultRequestTimeinsecs { get; set; }
        public string AverageConsultRequestTime { get; set; }
        public Nullable<int> AverageConsultRequestTimeinsecs { get; set; }
        public Nullable<int> ConsultCount { get; set; }
        public string TotalConsultTime { get; set; }
        public Nullable<int> TotalConsultTimeinsecs { get; set; }
        public string AverageConsultTime { get; set; }
        public Nullable<int> AverageConsultTimeinsecs { get; set; }
        public Nullable<int> Conference { get; set; }
        public Nullable<int> InboundCTQRequestCount { get; set; }
        public string TotalInboundCTQRequestTime { get; set; }
        public Nullable<int> TotalInboundCTQRequestTimeinsecs { get; set; }
        public Nullable<int> InboundCTQAnswerCount { get; set; }
        public string TotalInboundCTQAnswerTime { get; set; }
        public Nullable<int> TotalInboundCTQAnswerTimeinsecs { get; set; }
        public Nullable<int> OutdialCTQRequestCount { get; set; }
        public string TotalOutdialCTQRequestTime { get; set; }
        public Nullable<int> TotalOutdialCTQRequestTimeinsecs { get; set; }
        public Nullable<int> OutdialCTQAnswerCount { get; set; }
        public string TotalOutdialCTQAnswerTime { get; set; }
        public Nullable<int> TotalOutdialCTQAnswerTimeinsecs { get; set; }
        public Nullable<int> AgentTransfer { get; set; }
        public Nullable<int> AgentRequeue { get; set; }
        public Nullable<int> BlindTransfer { get; set; }
        public string InboundAvgHandleTime { get; set; }
        public Nullable<int> InboundAvgHandleTimeinsecs { get; set; }
        public string OutdialAvgHandleTime { get; set; }
        public Nullable<int> OutdialAvgHandleTimeinsecs { get; set; }
    }
}
