//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ampbi.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dim_Employee_Details1
    {
        public int EmployeeDetailid { get; set; }
        public string EmployeeFirstName { get; set; }
        public string EmployeelastName { get; set; }
        public string Title { get; set; }
        public string Supervisor { get; set; }
        public string SystemName { get; set; }
        public string SystemID { get; set; }
        public string PrimaryAssignedProgram { get; set; }
        public string OtherProgram { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Createdby { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Updatedby { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
