//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ampbi.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dim_Employee1
    {
        public int Employeenumber { get; set; }
        public string Companyguid { get; set; }
        public string LocationName { get; set; }
        public string employeeFirstname { get; set; }
        public string employeeLastname { get; set; }
        public string EMAIL { get; set; }
        public string Employeetitle { get; set; }
        public string mgr_lev1_name { get; set; }
        public string assignedprimaryprogram { get; set; }
        public Nullable<int> mgr_lev1_id { get; set; }
    }
}
