//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ampbi.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoalData
    {
        public int Goalid { get; set; }
        public string Companyguid { get; set; }
        public string ProgramName { get; set; }
        public string LOB { get; set; }
        public string Goalname { get; set; }
        public Nullable<decimal> Goalvalue { get; set; }
    }
}
