//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ampbi.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_charts_axislabels
    {
        public int tblseq { get; set; }
        public string companyguid { get; set; }
        public string modulename { get; set; }
        public string ChartName { get; set; }
        public string xaxislabel { get; set; }
        public string yaxislabel { get; set; }
        public Nullable<int> chartno { get; set; }
    }
}
