//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ampbi.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stg_Dim_Employee
    {
        public int Stgemplid { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string SiteName { get; set; }
        public string ActiveDirectoryID { get; set; }
        public string EmployeeFirstName { get; set; }
        public string EmployeeLastName { get; set; }
        public string Email { get; set; }
        public string EmployeeTitle { get; set; }
        public Nullable<int> Mgr_ID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public string PrimaryProgram { get; set; }
        public Nullable<int> PBXid { get; set; }
        public bool Processed { get; set; }
    }
}
