//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ampbi.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_companymodule
    {
        public int companymoduleid { get; set; }
        public string CompanyGUID { get; set; }
        public Nullable<int> moduleid { get; set; }
        public string DisplayName { get; set; }
    }
}
