//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ampbi.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserRegistrationFollowup
    {
        public int USRFLWPSeq { get; set; }
        public int USRSeq { get; set; }
        public string CompanyGUID { get; set; }
        public Nullable<System.DateTime> ContactDate { get; set; }
        public string Notes { get; set; }
        public string ContactedBy { get; set; }
        public Nullable<System.DateTime> Contactedon { get; set; }
        public string OutCome { get; set; }
    }
}
