//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ampbi.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_coaching
    {
        public int coachingid { get; set; }
        public string CompanyGuid { get; set; }
        public string Email { get; set; }
        public Nullable<int> EmployeeNumber { get; set; }
        public Nullable<System.DateTime> CoachingAssignedDate { get; set; }
        public Nullable<int> KPIMetricId { get; set; }
        public string Reason { get; set; }
        public Nullable<int> Goal { get; set; }
        public Nullable<int> commitment { get; set; }
        public Nullable<int> Actual { get; set; }
        public Nullable<System.DateTime> CoachingCompletionDate { get; set; }
        public byte[] Recording { get; set; }
        public string type { get; set; }
        public string articlename { get; set; }
        public Nullable<System.DateTime> TargetedCompletionDate { get; set; }
    }
}
