//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ampbi.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserRegistration
    {
        public int USRSeq { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public string CompanyName { get; set; }
        public string CompanyGUID { get; set; }
        public byte[] Logo { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<int> Zip { get; set; }
        public string ContactPhone { get; set; }
        public string PrefferedContactMethod { get; set; }
        public Nullable<int> NoOfEmployee { get; set; }
        public Nullable<int> NoOfLicence { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string RecordStatus { get; set; }
    }
}
