//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ampbi.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_empperfdata
    {
        public string CompanyGUID { get; set; }
        public Nullable<int> AgentID { get; set; }
        public string MetricName { get; set; }
        public string value { get; set; }
        public string goal { get; set; }
        public string PercentageToGoal { get; set; }
        public string Period { get; set; }
        public Nullable<System.DateTime> Current_Date { get; set; }
        public Nullable<int> Offset { get; set; }
        public string Tenure { get; set; }
        public Nullable<int> Manager_Level_Id { get; set; }
        public string emp_last_name { get; set; }
        public string emp_first_name { get; set; }
        public int RowID { get; set; }
        public string employee_name { get; set; }
    }
}
