//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ampbi.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_licencemoduleInfo
    {
        public int Licencemoduleseq { get; set; }
        public string Licencekey { get; set; }
        public string CompanyGUID { get; set; }
        public Nullable<int> Moduleid { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
