//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ampbi.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CompanyChartInfo
    {
        public int cciseq { get; set; }
        public string CompanyGUID { get; set; }
        public int ModuleID { get; set; }
        public Nullable<bool> Chart1 { get; set; }
        public string Chart1Name { get; set; }
        public Nullable<bool> Chart2 { get; set; }
        public string Chart2Name { get; set; }
        public Nullable<bool> Chart3 { get; set; }
        public string Chart3Name { get; set; }
        public Nullable<bool> Chart4 { get; set; }
        public string Chart4Name { get; set; }
    }
}
