//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ampbi.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_moodicontransaction
    {
        public int TransactionId { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Datecreated { get; set; }
        public string Moodiconselected { get; set; }
    }
}
