//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ampbi.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_noofchartsbydbcompany
    {
        public int tblseq { get; set; }
        public string Modulename { get; set; }
        public Nullable<int> NoOfCharts { get; set; }
        public Nullable<bool> isactive { get; set; }
        public string companyGUID { get; set; }
        public string ChartDisplayName { get; set; }
    }
}
