//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ampbi.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AppLog
    {
        public int logSeq { get; set; }
        public string CompanyGUID { get; set; }
        public string UserEmailID { get; set; }
        public string PropertyName1 { get; set; }
        public string PropertyValue1 { get; set; }
        public string PropertyName2 { get; set; }
        public string PropertyValue2 { get; set; }
        public string PropertyName3 { get; set; }
        public string PropertyValue3 { get; set; }
        public string PropertyName4 { get; set; }
        public string PropertyValue4 { get; set; }
        public string PropertyName5 { get; set; }
        public string PropertyValue5 { get; set; }
        public string PropertyName6 { get; set; }
        public string PropertyValue6 { get; set; }
        public string PropertyName7 { get; set; }
        public string PropertyValue7 { get; set; }
        public string PropertyName8 { get; set; }
        public string PropertyValue8 { get; set; }
        public string DashboardName { get; set; }
    }
}
