//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ampbi.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UesSurveyData
    {
        public int SurveyDataid { get; set; }
        public Nullable<int> T_MONTH { get; set; }
        public Nullable<int> t_year { get; set; }
        public string T_WEEK { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> Tenure { get; set; }
        public string Tenurity { get; set; }
        public string LOB { get; set; }
        public string TranTime { get; set; }
        public string Interval { get; set; }
        public Nullable<System.DateTime> TranDate { get; set; }
        public string Sites { get; set; }
        public Nullable<int> AgentID { get; set; }
        public Nullable<int> Skill { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<int> Q1 { get; set; }
        public Nullable<int> Q2 { get; set; }
        public Nullable<int> Q3 { get; set; }
        public Nullable<int> Q4 { get; set; }
        public Nullable<int> Q5 { get; set; }
        public Nullable<int> Q6 { get; set; }
        public Nullable<int> Q7 { get; set; }
        public Nullable<int> Q8 { get; set; }
        public Nullable<int> Q9 { get; set; }
        public Nullable<int> Q10 { get; set; }
        public Nullable<int> Q11 { get; set; }
        public Nullable<int> Q12 { get; set; }
        public Nullable<int> Q13 { get; set; }
        public Nullable<int> Q14 { get; set; }
        public Nullable<int> Q15 { get; set; }
        public Nullable<int> Q16 { get; set; }
        public Nullable<int> Q17 { get; set; }
        public Nullable<int> Q18 { get; set; }
        public Nullable<int> LengthOfCall { get; set; }
        public string Products { get; set; }
        public string feedbacktext { get; set; }
    }
}
